"""drop agent_heartbeats table

Revision ID: 5b1afa8b5967
Revises: f373234b15f8
Create Date: 2026-08-13 00:15:41.067468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1afa8b5967'
down_revision: Union[str, Sequence[str], None] = 'f373234b15f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_heartbeats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_heartbeats',
    sa.Column('agent_instance_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False, comment='healthy | degraded | dead'),
    sa.PrimaryKeyConstraint('agent_instance_id', name=op.f('agent_heartbeats_pkey'))
    )
    # ### end Alembic commands ###
