"""initial schema

Revision ID: f373234b15f8
Revises: 
Create Date: 2026-08-06 19:17:55.176542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f373234b15f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_heartbeats',
    sa.Column('agent_instance_id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False, comment='healthy | degraded | dead'),
    sa.PrimaryKeyConstraint('agent_instance_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, comment='Current FSM state - validated upstream by incident_fsm.py. not here'),
    sa.Column('detection_mode', sa.Enum('K8S_ONLY', 'OBSERVABILITY_ONLY', 'FULL', name='detection_mode_enum'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Original Observer payload'),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('proposed_action', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True, comment='config_change | live_action'),
    sa.Column('verification_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{passed, reason, checks_run, warnings} - mirrrors VerificationResult'),
    sa.Column('blast_radius_score', sa.Integer(), nullable=True),
    sa.Column('operator_decision', sa.String(), nullable=True, comment='approved | rejected'),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('postmortem', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_fingerprint', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Last time this fingerprint fired — updated on every increment'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_fingerprint', 'namespace', name='uq_rate_limit_fingerprint_namespace')
    )
    op.create_table('runbook_stats',
    sa.Column('runbook_id', sa.String(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('total_mttr_sec', sa.BigInteger(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('runbook_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('agent_instance_id', sa.String(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('blast_radius', sa.Integer(), nullable=True),
    sa.Column('policy_result', sa.String(), nullable=True),
    sa.Column('operator_decision', sa.String(), nullable=True),
    sa.Column('topology_source', sa.String(), nullable=True, comment='discovered | static | unavailable'),
    sa.Column('detection_mode', sa.Enum('K8S_ONLY', 'OBSERVABILITY_ONLY', 'FULL', name='detection_mode_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full context - approval payload, rejection reason, etc'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_incident_id', 'audit_logs', ['incident_id'], unique=False)
    op.create_table('remediation_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('runbook_id', sa.String(), nullable=False),
    sa.Column('rendered_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rollback_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cluster_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False, comment='planned | executing | rolled_back | complete'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_remediation_states_incident_id', 'remediation_states', ['incident_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False, comment="e.g. 'remediator'"),
    sa.Column('agent_instance_id', sa.String(), nullable=False, comment='e.g. "remediator-2" -specific replica'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Small summary only'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_incident_timestamp', 'timeline_events', ['incident_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_events_incident_timestamp', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_remediation_states_incident_id', table_name='remediation_states')
    op.drop_table('remediation_states')
    op.drop_index('ix_audit_logs_incident_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('runbook_stats')
    op.drop_table('rate_limit_records')
    op.drop_table('incidents')
    op.drop_table('agent_heartbeats')
    # ### end Alembic commands ###
